### PR TITLE
authentication database & mongo 3.0

### PR DESCRIPTION
**Pull request by amoschov**

### CODE REVIEW

**Comment by d0x** [comment]
+1 for that! That fixes #50  as well. I would love to see that @amoschov . Thank you!

**Comment by epishkin** [comment]
Thanks for the p/r! I will review and merge this week.

**Comment by fracz** [comment]
+1

**Comment by d0x** [comment]
Hey @epishkin . Any plan when to go on?

**Comment by d0x** [comment]
Hey @epishkin , can u please give us a direction when you going to merge and release it?

**Comment by epishkin** [comment]
let me resolve merge conflicts first :-)

**Comment by epishkin** [comment]
@d0x rebased and merged to master. Travis build is green - 
https://travis-ci.org/secondmarket/mongeez/builds/70742402

Sorry I had to remove the commit with aws plugin. If you really want it make a different p/r please.

**Comment by d0x** [comment]
Wuhuu, thank you ;D

**Comment by fracz** [comment]
Can you bump version number to 0.9.5 including this PR?

**Comment by prateekpatil** [comment]
Hello @d0x / @amoschov / @epishkin   Please can you guys bump up the version, as this is blocking us to update mogno driver in our code base. Thanks

**Comment by pandey-vikesh** [comment]
guys, many people have been requesting you ppl to release and publish this new version 0.9.5 as lot of people and their project's are blocked due to this.

**Comment by epishkin** [comment]
0.9.5 has been released :smiley: 
http://repo1.maven.org/maven2/org/mongeez/mongeez/0.9.5/

**Comment by pandey-vikesh** [comment]
awesome. Looks like my Christmas has started bit early. Thanks a lot. works like a charm :). I see 0.9.6 published as well. Though i could not find any release notes as to what changes are there in 0.9.6. So i resorted to 0.9.5

Cheers,
Vikesh

**Comment by epishkin** [comment]
This is open source. Feel free to contribute release notes to the project! :-)

**Pull request closed without merging**
